# Dayton Public Schools audit data analytic notebook
|       NOTES         |                                          |
|---------------------|----------------------------------------- |
| Started on          | 09/24/2026                               |
| Data provided by    |                                          |
| GL accounting system|                                          |
| PR accounting system|                                          |

## Imports and variables

In [16]:
import pandas as pd
import numpy as np
from shutil import copyfile
import xlwings as xw
import os
# os.chdir(r"C:\Users\AMDrummonds\Python_projects\dayton_public_schools")
print(os.getcwd())  # Confirms the current directory

c:\Users\AMDrummonds\Python_projects\dayton_public_schools

In [ ]:
year = '2026'
# GL FILES
# I changed the folder to where the file are to C:\Users\AMDrummonds\Python_projects\dayton_public_schools

fund_report = r'data\June 30 2026 Cash Position Report.xlsx'
fund_report_prev = r'data\June 30 2025 Cash Position Report.xlsx'
exp_loc = r'data\June 30 2026 Expense Detail Report.xlsx'
exp_loc_prev = r'data\June 30 2025 Expense Detail Report.xlsx'
rev_loc = r'data\June 30 2026 Receipt Detail Report.xlsx'
rev_loc_prev  = r'data\June 30 2025 Receipt Detail Report.xlsx'

:

## GL work

### clean fund report

In [ ]:
# change pandas to display all columns
pd.set_option('display.max_columns', None)
# change pandas to display floats to 2 decimal places
pd.set_option('display.float_format', lambda x: '%.2f' % x)

:

In [ ]:
# -------------------------------------------------
# Build fund_report_df from the Excel fund report
# -------------------------------------------------
fund_report_df = pd.read_excel(fund_report, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
fund_report_df.columns = (
    fund_report_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "beginning_balance",
    "receipts_ytd",
    "receipts_mtd",
    "expenditures_ytd",
    "expenditures_mtd",
    "current_balance",
    "encumbrances",
    "unencumbered_cash",
]

fund_report_df[money_cols] = (
    fund_report_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(fund_report_df.head(10))

,fund,scc,opu,desc,beginning_balance,receipts_ytd,receipts_mtd,expenditures_ytd,expenditures_mtd,current_balance,encumbrances,unencumbered_cash,as_of
0,001,NaN,NaN,General,"$92,990,749.77","$281,246,157.46","$13,818,483.32","$260,110,066.80","$20,990,041.70","$114,126,840.43","$9,502,745.20","$104,624,095.23",June 2026
1,002,NaN,NaN,Debt Retirement,"$21,795,148.46","$13,739,921.66",$0.00,"$13,176,034.25",$0.00,"$22,359,035.87",$0.00,"$22,359,035.87",June 2026
2,003,0000,NaN,Permanent Improvement - Revenue and Bala,"$-10,034,241.71",$0.00,$0.00,$0.00,$0.00,"$-10,034,241.71",$0.00,"$-10,034,241.71",June 2026
3,003,1220,NaN,Permanent Improvement - Budget Departmen,"$13,166,860.81",$0.00,$0.00,$0.00,$0.00,"$13,166,860.81",$0.00,"$13,166,860.81",June 2026
4,003,1510,NaN,Permanent Improvement - Elementary Schoo,"$-123,599.58",$0.00,$0.00,$0.00,$0.00,"$-123,599.58",$0.00,"$-123,599.58",June 2026
5,003,1950,NaN,Permanent Improvement - Safety Security,"$-556,656.46",$0.00,$0.00,$0.00,$0.00,"$-556,656.46",$0.00,"$-556,656.46",June 2026
6,003,2001,NaN,Permanent Improvement - Treasurer Manage,"$72,460,581.36","$803,626.26",$0.00,$0.00,$0.00,"$73,264,207.62",$0.00,"$73,264,207.62",June 2026
7,003,2002,NaN,Permanent Improvement - District Fixed C,"$-5,679,967.46",$0.00,$0.00,"$16,199.99",$0.00,"$-5,696,167.45",$0.00,"$-5,696,167.45",June 2026
8,003,2005,NaN,Permanent Improvement - Equipment Acquis,"$-36,246,292.54",$0.00,$0.00,"$1,544,318.76",$0.00,"$-37,790,611.30",$0.00,"$-37,790,611.30",June 2026
9,003,2009,NaN,Permanent Improvement - Swap,"$3,384,513.20",$0.00,$0.00,$0.00,$0.00,"$3,384,513.20",$0.00,"$3,384,513.20",June 2026

:

In [ ]:
# -------------------------------------------------
# Build fund_report_prev_df from the Excel fund report
# -------------------------------------------------
fund_report_prev_df = pd.read_excel(fund_report_prev, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
fund_report_prev_df.columns = (
    fund_report_prev_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "beginning_balance",
    "receipts_ytd",
    "receipts_mtd",
    "expenditures_ytd",
    "expenditures_mtd",
    "current_balance",
    "encumbrances",
    "unencumbered_cash",
]

fund_report_prev_df[money_cols] = (
    fund_report_prev_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(fund_report_df.head(10))

,fund,scc,opu,desc,beginning_balance,receipts_ytd,receipts_mtd,expenditures_ytd,expenditures_mtd,current_balance,encumbrances,unencumbered_cash,as_of
0,001,NaN,NaN,General,"$92,990,749.77","$281,246,157.46","$13,818,483.32","$260,110,066.80","$20,990,041.70","$114,126,840.43","$9,502,745.20","$104,624,095.23",June 2026
1,002,NaN,NaN,Debt Retirement,"$21,795,148.46","$13,739,921.66",$0.00,"$13,176,034.25",$0.00,"$22,359,035.87",$0.00,"$22,359,035.87",June 2026
2,003,0000,NaN,Permanent Improvement - Revenue and Bala,"$-10,034,241.71",$0.00,$0.00,$0.00,$0.00,"$-10,034,241.71",$0.00,"$-10,034,241.71",June 2026
3,003,1220,NaN,Permanent Improvement - Budget Departmen,"$13,166,860.81",$0.00,$0.00,$0.00,$0.00,"$13,166,860.81",$0.00,"$13,166,860.81",June 2026
4,003,1510,NaN,Permanent Improvement - Elementary Schoo,"$-123,599.58",$0.00,$0.00,$0.00,$0.00,"$-123,599.58",$0.00,"$-123,599.58",June 2026
5,003,1950,NaN,Permanent Improvement - Safety Security,"$-556,656.46",$0.00,$0.00,$0.00,$0.00,"$-556,656.46",$0.00,"$-556,656.46",June 2026
6,003,2001,NaN,Permanent Improvement - Treasurer Manage,"$72,460,581.36","$803,626.26",$0.00,$0.00,$0.00,"$73,264,207.62",$0.00,"$73,264,207.62",June 2026
7,003,2002,NaN,Permanent Improvement - District Fixed C,"$-5,679,967.46",$0.00,$0.00,"$16,199.99",$0.00,"$-5,696,167.45",$0.00,"$-5,696,167.45",June 2026
8,003,2005,NaN,Permanent Improvement - Equipment Acquis,"$-36,246,292.54",$0.00,$0.00,"$1,544,318.76",$0.00,"$-37,790,611.30",$0.00,"$-37,790,611.30",June 2026
9,003,2009,NaN,Permanent Improvement - Swap,"$3,384,513.20",$0.00,$0.00,$0.00,$0.00,"$3,384,513.20",$0.00,"$3,384,513.20",June 2026

:

## Clean expense file

In [ ]:
# -------------------------------------------------
# Build fund_report_df from the Excel fund report
# -------------------------------------------------
exp_loc_df = pd.read_excel(exp_loc, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
exp_loc_df.columns = (
    exp_loc_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(".", "", regex=False)
)

# Split "Fund: 001 - General" into its code and name.
fund_parts = exp_loc_df["fund"].astype("string").str.extract(
    r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
)
exp_loc_df["fund"] = fund_parts["fund"].fillna(
    exp_loc_df["fund"].astype("string").str.strip()
)
exp_loc_df["fund_name"] = fund_parts["fund_name"]

# Split "Function: 0000 - Not Applicable" into its code and name.
function_parts = exp_loc_df["function"].astype("string").str.extract(
    r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
)
exp_loc_df["function"] = function_parts["function"].fillna(
    exp_loc_df["function"].astype("string").str.strip()
)
exp_loc_df["function_name"] = function_parts["function_name"]

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "debit",
    "credit",
    "balance",
]

exp_loc_df[money_cols] = (
    exp_loc_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(exp_loc_df.head(10))

,fund,special_cost_center,function,opu,account,gl_reference,description,posting_date,ss,ref2,peid,ck_id,ck_no,debit,credit,balance,fund_name,function_name
0,001,2007,0000,000,001-0000-4510000-2007-000000-000-00,JE09366,Board Approved Perm Transfers,9/16/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$13,204,156.73","$-13,204,156.73",General,Not Applicable
1,001,2007,0000,000,001-0000-4510000-2007-000000-000-00,JE09366,Board Approved Perm Transfers,9/16/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$25,000,000.00","$-25,000,000.00",General,Not Applicable
2,001,2007,0000,000,001-0000-4510000-2007-000000-000-00,JE09367,Permanent transfer - Board app,9/16/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$3,930.00","$-3,930.00",General,Not Applicable
3,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09349,Return of Advance,8/29/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$2,083,563.30","$-2,083,563.30",General,Not Applicable
4,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09484,Repay ECE Advance,11/25/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$162,469.80","$-162,469.80",General,Not Applicable
5,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09524,Repay Board Advances T1 Delinq,12/5/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$16,498.58","$-16,498.58",General,Not Applicable
6,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09540,Repay Board Advance Career Tec,12/19/2025,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$60,657.89","$-60,657.89",General,Not Applicable
7,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09554,Repay board advance,1/20/2026,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$19,382.06","$-19,382.06",General,Not Applicable
8,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09554,Repay board advance,1/20/2026,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$5,011.37","$-5,011.37",General,Not Applicable
9,001,2007,0000,000,001-0000-4522000-2007-000000-000-00,JE09554,Repay board advance,1/20/2026,JE,NaN,N/A..N/A,NaN,NaN,$0.00,"$48,771.79","$-48,771.79",General,Not Applicable

:

In [ ]:
# -------------------------------------------------
# Build fund_report_df from the Excel fund report
# -------------------------------------------------
exp_loc_prev_df = pd.read_excel(exp_loc_prev, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
exp_loc_prev_df.columns = (
    exp_loc_prev_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(".", "", regex=False)
)

# Split "Fund: 001 - General" into its code and name.
fund_parts = exp_loc_prev_df["fund"].astype("string").str.extract(
    r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
)
exp_loc_prev_df["fund"] = fund_parts["fund"].fillna(
    exp_loc_prev_df["fund"].astype("string").str.strip()
)
exp_loc_prev_df["fund_name"] = fund_parts["fund_name"]

# Split "Function: 0000 - Not Applicable" into its code and name.
function_parts = exp_loc_prev_df["function"].astype("string").str.extract(
    r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
)
exp_loc_prev_df["function"] = function_parts["function"].fillna(
    exp_loc_prev_df["function"].astype("string").str.strip()
)
exp_loc_prev_df["function_name"] = function_parts["function_name"]

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "debit",
    "credit",
    "balance",
]

exp_loc_prev_df[money_cols] = (
    exp_loc_prev_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(exp_loc_prev_df.head(10))

,fund,special_cost_center,function,opu,account,gl_reference,description,posting_date,ss,ref2,peid,ck_id,ck_no,debit,credit,balance,fund_name,function_name
0,001,3020,0000,500,001-0000-5211000-3020-000000-500-00,01020DP,1.0000.3020.500,1/17/2025,2,CONT REG,N/A..N/A,NaN,NaN,$63.00,$0.00,$63.00,General,Not Applicable
1,001,3020,0000,500,001-0000-5223000-3020-000000-500-00,01020DP,1.0000.3020.500,1/17/2025,2,CONT REG,N/A..N/A,NaN,NaN,$6.34,$0.00,$6.34,General,Not Applicable
2,001,3020,0000,500,001-0000-5262000-3020-000000-500-00,01020DP,1.0000.3020.500,1/17/2025,2,CONT REG,N/A..N/A,NaN,NaN,$2.26,$0.00,$2.26,General,Not Applicable
3,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN06012024,SCHWABE STUDIO PO disencumbere,7/11/2024,OH,NaN,V000530,AP,00279632,$458.00,$0.00,$458.00,General,Regular Instruction
4,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN79792,"OREGON PRINTING 1,300 2024 Com",10/1/2024,OH,P042699,V026468,AP,00281662,$747.33,$0.00,$747.33,General,Regular Instruction
5,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN79792,OREGON PRINTING Increase per P,10/1/2024,OH,P042699,V026468,AP,00281662,$54.77,$0.00,$54.77,General,Regular Instruction
6,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN1581968,STERLING PAPERS 8.5 x 11 White,10/22/2024,OH,P044314,V002417,AP,00282269,"$2,799.20",$0.00,"$2,799.20",General,Regular Instruction
7,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN35153353,JOSTENS INC Open Order for 202,11/12/2024,OH,P044451,V001034,AP,00282857,$924.00,$0.00,$924.00,General,Regular Instruction
8,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN1595910,STERLING PAPERS 8.5 x 11 White,12/26/2024,OH,P045047,V002417,AP,00283894,"$2,799.20",$0.00,"$2,799.20",General,Regular Instruction
9,001,1530,1100,271,001-1100-5461000-1530-000000-271-00,IN36553458,JOSTENS INC Open Order for 202,4/10/2025,OH,P044451,V001034,AP,00286436,$45.15,$0.00,$45.15,General,Regular Instruction

:

## Clean revenue file

In [ ]:
# -------------------------------------------------
# Build rev_loc_df from the Excel revenue location report
# -------------------------------------------------
rev_loc_df = pd.read_excel(rev_loc, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
rev_loc_df.columns = (
    rev_loc_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(".", "", regex=False)
)

# Split "Fund: 001 - General" into its code and name.
fund_parts = rev_loc_df["fund"].astype("string").str.extract(
    r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
)
rev_loc_df["fund"] = fund_parts["fund"].fillna(
    rev_loc_df["fund"].astype("string").str.strip()
)
rev_loc_df["fund_name"] = fund_parts["fund_name"]

# Split "Function: 0000 - Not Applicable" into its code and name.
function_parts = rev_loc_df["function"].astype("string").str.extract(
    r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
)
rev_loc_df["function"] = function_parts["function"].fillna(
    rev_loc_df["function"].astype("string").str.strip()
)
rev_loc_df["function_name"] = function_parts["function_name"]

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "debit",
    "credit",
    "balance",
]

rev_loc_df[money_cols] = (
    rev_loc_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(rev_loc_df.head(10))

,fund,special_cost_center,function,opu,account,exp/rev,gl_reference,description,posting_date,ss,ref2,peid,ck_id,ck_no,debit,credit,balance,fund_name,function_name
0,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,8864,Cash Receipts I gainwell techn,7/10/2025,CR,129078,ZZBLANK,GD,NaN,$0.00,"$64,762.98","$-64,762.98",General,Not Applicable
1,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,8874,Cash Receipts I gainwell techn,7/24/2025,CR,129094,ZZBLANK,GD,NaN,$0.00,"$50,983.01","$-50,983.01",General,Not Applicable
2,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,8894,Cash Receipts I gainwell techn,8/14/2025,CR,129144,ZZBLANK,GD,NaN,$0.00,"$10,328.18","$-10,328.18",General,Not Applicable
3,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,8906,Cash Receipts I gainwell techn,8/22/2025,CR,129172,ZZBLANK,GD,NaN,$0.00,"$1,825,686.12","$-1,825,686.12",General,Not Applicable
4,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,9059,Cash Receipts I gainwell techn,10/2/2025,CR,129698,ZZBLANK,GD,NaN,$0.00,"$10,767.82","$-10,767.82",General,Not Applicable
5,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,9084,Cash Receipts I gainwell techn,10/9/2025,CR,129799,ZZBLANK,GD,NaN,$0.00,"$12,343.07","$-12,343.07",General,Not Applicable
6,001,1925,0000,000,001-0000-4412000-1925-000000-000-00,4,9113,Cash Receipts I gainwell tech,10/17/2025,CR,129896,ZZBLANK,GD,NaN,$0.00,"$1,736.10","$-1,736.10",General,Not Applicable
7,001,1925,0000,000,001-0000-4422100-1925-000000-000-00,4,9166,Cash Receipts I gainwell techn,11/30/2025,CR,130101,ZZBLANK,GD,NaN,$0.00,"$7,791.08","$-7,791.08",General,Not Applicable
8,001,1925,0000,000,001-0000-4422100-1925-000000-000-00,4,9206,Cash Receipts I gainwell techn,12/4/2025,CR,130237,ZZBLANK,GD,NaN,$0.00,"$8,119.08","$-8,119.08",General,Not Applicable
9,001,1925,0000,000,001-0000-4422100-1925-000000-000-00,4,9274,Cash Receipts I gainwell techn,12/26/2025,CR,130442,ZZBLANK,GD,NaN,$0.00,"$24,335.41","$-24,335.41",General,Not Applicable

:

## Revenue_Previous

In [ ]:
# -------------------------------------------------
# Build rev_loc_prev_df from the Excel revenue location report
# -------------------------------------------------
rev_loc_prev_df = pd.read_excel(rev_loc_prev, dtype=str).copy()

# Lowercase column names and replace spaces with underscores
rev_loc_prev_df.columns = (
    rev_loc_prev_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(".", "", regex=False)
)

# Split "Fund: 001 - General" into its code and name.
fund_parts = rev_loc_prev_df["fund"].astype("string").str.extract(
    r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
)
rev_loc_prev_df["fund"] = fund_parts["fund"].fillna(
    rev_loc_prev_df["fund"].astype("string").str.strip()
)
rev_loc_prev_df["fund_name"] = fund_parts["fund_name"]

# Split "Function: 0000 - Not Applicable" into its code and name.
function_parts = rev_loc_prev_df["function"].astype("string").str.extract(
    r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
)
rev_loc_prev_df["function"] = function_parts["function"].fillna(
    rev_loc_prev_df["function"].astype("string").str.strip()
)
rev_loc_prev_df["function_name"] = function_parts["function_name"]

# Convert money columns to numbers and round to two decimal places
money_cols = [
    "debit",
    "credit",
    "balance",
]

rev_loc_prev_df[money_cols] = (
    rev_loc_prev_df[money_cols]
    .apply(pd.to_numeric, errors="coerce")
    .round(2)
)

# Display regular dollar amounts instead of scientific notation.
# This does not change the numeric values in the DataFrame.
with pd.option_context("display.float_format", "${:,.2f}".format):
    display(rev_loc_prev_df.head(10))

,fund,special_cost_center,function,opu,account,gl_reference,description,posting_date,ss,ref2,peid,ck_id,ck_no,debit,credit,balance,fund_name,function_name
0,001,3025,0000,000,001-0000-4182000-3025-000000-000-00,200957,Cash Receipts I seedling stive,2/28/2025,CR,128261,ZZBLANK,GD,NaN,$0.00,"$7,851.50","$-7,851.50",General,Not Applicable
1,001,3025,0000,000,001-0000-4182000-3025-000000-000-00,204858,Cash Receipts I seedling stive,4/17/2025,CR,128636,ZZBLANK,GD,NaN,$0.00,"$4,868.75","$-4,868.75",General,Not Applicable
2,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8071,Cash Receipts I JV52 SF-14H Tu,7/26/2024,CR,126214,ZZBLANK,GD,NaN,$0.00,"$8,817.38","$-8,817.38",General,Not Applicable
3,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8114,CASH RECEIPTS I JV52 SF-14H Tu,8/31/2024,CR,126352,ZZBLANK,GD,NaN,$0.00,"$4,669.28","$-4,669.28",General,Not Applicable
4,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8203,Cash Receipts I JV52 SF-14H Tu,9/27/2024,CR,126767,ZZBLANK,GD,NaN,$0.00,"$229,812.95","$-229,812.95",General,Not Applicable
5,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8629,Cash Receipts I JV98 SF6 Exces,2/21/2025,CR,128226,ZZBLANK,GD,NaN,$0.00,"$201,550.94","$-201,550.94",General,Not Applicable
6,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8682,Cash Receipts I jv52 sf14h tui,3/21/2025,CR,128471,ZZBLANK,GD,NaN,$0.00,"$176,627.89","$-176,627.89",General,Not Applicable
7,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8682,Cash Receipts I jv98 sf6 exces,3/21/2025,CR,128471,ZZBLANK,GD,NaN,$0.00,"$387,047.42","$-387,047.42",General,Not Applicable
8,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8736,Cash Receipts I JV52 SF-14H Tu,4/18/2025,CR,128660,ZZBLANK,GD,NaN,$0.00,"$22,978.97","$-22,978.97",General,Not Applicable
9,001,4502,0000,500,001-0000-4122300-4502-000000-500-00,8808,Cash Receipts I JV52 SF-14H Tu,5/23/2025,CR,128966,ZZBLANK,GD,NaN,$0.00,"$11,435.42","$-11,435.42",General,Not Applicable

:

## GL Fund

In [ ]:
fund_report_comparison = fund_report_df.merge(
    fund_report_prev_df,
    on="fund",
    how="outer",
    suffixes=("_current", "_prev"),
)

# Use the current description when available; otherwise use the previous one.
fund_report_comparison["desc"] = (
    fund_report_comparison["desc_current"]
    .fillna(fund_report_comparison["desc_prev"])
)

fund_report_comparison = fund_report_comparison[
    [
        "fund",
        "desc",
        "beginning_balance_prev",
        "receipts_ytd_prev",
        "expenditures_ytd_prev",
        "current_balance_prev",
        "beginning_balance_current",
        "receipts_ytd_current",
        "expenditures_ytd_current",
        "current_balance_current",
    ]
]

with pd.option_context("display.float_format", "${:,.2f}".format):
    display(fund_report_comparison.head(10))

,fund,desc,beginning_balance_prev,receipts_ytd_prev,expenditures_ytd_prev,current_balance_prev,beginning_balance_current,receipts_ytd_current,expenditures_ytd_current,current_balance_current
0,001,General,"$139,170,994.14","$241,710,099.78","$287,890,344.15","$92,990,749.77","$92,990,749.77","$281,246,157.46","$260,110,066.80","$114,126,840.43"
1,002,Debt Retirement,"$20,917,669.74","$14,046,107.59","$13,168,628.87","$21,795,148.46","$21,795,148.46","$13,739,921.66","$13,176,034.25","$22,359,035.87"
2,003,Permanent Improvement - Revenue and Bala,"$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
3,003,Permanent Improvement - Revenue and Bala,"$13,166,860.81",$0.00,$0.00,"$13,166,860.81","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
4,003,Permanent Improvement - Revenue and Bala,"$-123,599.58",$0.00,$0.00,"$-123,599.58","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
5,003,Permanent Improvement - Revenue and Bala,"$-556,656.46",$0.00,$0.00,"$-556,656.46","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
6,003,Permanent Improvement - Revenue and Bala,"$71,558,013.43","$902,567.93",$0.00,"$72,460,581.36","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
7,003,Permanent Improvement - Revenue and Bala,"$-5,665,460.02",$0.00,"$14,507.44","$-5,679,967.46","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
8,003,Permanent Improvement - Revenue and Bala,"$-34,701,498.78",$0.00,"$1,544,793.76","$-36,246,292.54","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
9,003,Permanent Improvement - Revenue and Bala,"$3,384,513.20",$0.00,$0.00,"$3,384,513.20","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"

:

## GL Fund scc

In [ ]:
fund_report_scc_comparison = fund_report_df.merge(
    fund_report_prev_df,
    on="fund",
    how="outer",
    suffixes=("_current", "_prev"),
)

# Prefer current values; use previous values for funds absent from current.
fund_report_scc_comparison["scc"] = (
    fund_report_scc_comparison["scc_current"]
    .fillna(fund_report_scc_comparison["scc_prev"])
)
fund_report_scc_comparison["desc"] = (
    fund_report_scc_comparison["desc_current"]
    .fillna(fund_report_scc_comparison["desc_prev"])
)

fund_report_scc_comparison = fund_report_scc_comparison[
    [
        "fund",
        "scc",
        "desc",
        "beginning_balance_prev",
        "receipts_ytd_prev",
        "expenditures_ytd_prev",
        "current_balance_prev",
        "beginning_balance_current",
        "receipts_ytd_current",
        "expenditures_ytd_current",
        "current_balance_current",
    ]
]

with pd.option_context("display.float_format", "${:,.2f}".format):
    display(fund_report_scc_comparison.head(10))

,fund,scc,desc,beginning_balance_prev,receipts_ytd_prev,expenditures_ytd_prev,current_balance_prev,beginning_balance_current,receipts_ytd_current,expenditures_ytd_current,current_balance_current
0,001,NaN,General,"$139,170,994.14","$241,710,099.78","$287,890,344.15","$92,990,749.77","$92,990,749.77","$281,246,157.46","$260,110,066.80","$114,126,840.43"
1,002,NaN,Debt Retirement,"$20,917,669.74","$14,046,107.59","$13,168,628.87","$21,795,148.46","$21,795,148.46","$13,739,921.66","$13,176,034.25","$22,359,035.87"
2,003,0000,Permanent Improvement - Revenue and Bala,"$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
3,003,0000,Permanent Improvement - Revenue and Bala,"$13,166,860.81",$0.00,$0.00,"$13,166,860.81","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
4,003,0000,Permanent Improvement - Revenue and Bala,"$-123,599.58",$0.00,$0.00,"$-123,599.58","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
5,003,0000,Permanent Improvement - Revenue and Bala,"$-556,656.46",$0.00,$0.00,"$-556,656.46","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
6,003,0000,Permanent Improvement - Revenue and Bala,"$71,558,013.43","$902,567.93",$0.00,"$72,460,581.36","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
7,003,0000,Permanent Improvement - Revenue and Bala,"$-5,665,460.02",$0.00,"$14,507.44","$-5,679,967.46","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
8,003,0000,Permanent Improvement - Revenue and Bala,"$-34,701,498.78",$0.00,"$1,544,793.76","$-36,246,292.54","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"
9,003,0000,Permanent Improvement - Revenue and Bala,"$3,384,513.20",$0.00,$0.00,"$3,384,513.20","$-10,034,241.71",$0.00,$0.00,"$-10,034,241.71"

:

## GL_2YR_REV

In [ ]:
import pandas as pd


# ============================================================
# MONEY COLUMNS
# ============================================================
money_cols = ["debit", "credit", "balance"]


# ============================================================
# PREPARE REVENUE LOCATION DATA
# ============================================================
def prepare_revenue_location(df):
    gl_2yr_rev_df = df.copy()

    # --------------------------------------------------------
    # Split Fund
    # Example:
    # "Fund: 001 - General"
    # becomes:
    # fund = 001
    # fund_name = General
    # --------------------------------------------------------
    fund_parts = gl_2yr_rev_df["fund"].astype("string").str.extract(
        r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
    )

    gl_2yr_rev_df["fund"] = fund_parts["fund"].fillna(
        gl_2yr_rev_df["fund"].astype("string").str.strip()
    )

    gl_2yr_rev_df["fund_name"] = fund_parts["fund_name"]

    # --------------------------------------------------------
    # Split Function
    # Example:
    # "Function: 0000 - Not Applicable"
    # becomes:
    # function = 0000
    # function_name = Not Applicable
    # --------------------------------------------------------
    function_parts = gl_2yr_rev_df["function"].astype("string").str.extract(
        r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
    )

    gl_2yr_rev_df["function"] = function_parts["function"].fillna(
        gl_2yr_rev_df["function"].astype("string").str.strip()
    )

    gl_2yr_rev_df["function_name"] = function_parts["function_name"]

    # --------------------------------------------------------
    # Convert money columns to numeric
    # --------------------------------------------------------
    for col in money_cols:
        gl_2yr_rev_df[col] = pd.to_numeric(
            gl_2yr_rev_df[col],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Total each Fund / Function combination
    # --------------------------------------------------------
    gl_2yr_rev_df = (
        gl_2yr_rev_df
        .groupby(
            ["fund", "function"],
            as_index=False,
            dropna=False
        )
        .agg(
            fund_name=("fund_name", "first"),
            function_name=("function_name", "first"),
            debit=(
                "debit",
                lambda values: values.sum(min_count=1)
            ),
            credit=(
                "credit",
                lambda values: values.sum(min_count=1)
            ),
            balance=(
                "balance",
                lambda values: values.sum(min_count=1)
            ),
        )
    )

    return gl_2yr_rev_df


# ============================================================
# PREPARE CURRENT YEAR
# ============================================================
current = prepare_revenue_location(
    rev_loc_df
)


# ============================================================
# PREPARE PREVIOUS YEAR
# ============================================================
previous = prepare_revenue_location(
    rev_loc_prev_df
)


# ============================================================
# MERGE CURRENT AND PREVIOUS YEAR
# ============================================================
rev_2yr_df = current.merge(
    previous,
    on=["fund", "function"],
    how="outer",
    suffixes=("_current", "_prev"),
    validate="one_to_one",
)


# ============================================================
# FUND NAME
# Prefer current-year name.
# If missing, use previous-year name.
# ============================================================
rev_2yr_df["fund_name"] = (
    rev_2yr_df["fund_name_current"]
    .fillna(rev_2yr_df["fund_name_prev"])
)


# ============================================================
# FUNCTION NAME
# Prefer current-year name.
# If missing, use previous-year name.
# ============================================================
rev_2yr_df["function_name"] = (
    rev_2yr_df["function_name_current"]
    .fillna(rev_2yr_df["function_name_prev"])
)


# ============================================================
# VARIANCE
# Current Year Credit - Previous Year Credit
# ============================================================
rev_2yr_df["variance"] = (
    rev_2yr_df["credit_current"]
    - rev_2yr_df["credit_prev"]
)


# ============================================================
# PERCENTAGE CHANGE
#
# (Current - Previous) / Previous * 100
#
# Previous-year amounts of zero are converted to NaN
# to avoid division-by-zero errors.
# ============================================================
rev_2yr_df["percentage"] = (
    rev_2yr_df["variance"]
    .div(
        rev_2yr_df["credit_prev"].replace(
            0,
            float("nan")
        )
    )
    .mul(100)
)


# ============================================================
# FINAL COLUMN ORDER
# ============================================================
rev_2yr_df = rev_2yr_df[
    [
        "fund",
        "fund_name",
        "function",
        "function_name",
        "credit_prev",
        "credit_current",
        "variance",
        "percentage",
    ]
].copy()


# ============================================================
# DISPLAY COPY
#
# Keep rev_2yr_df numeric.
# Only format the copy used for notebook display.
# ============================================================
display_df = rev_2yr_df.head(10).copy()


# Format dollar columns
for col in [
    "credit_prev",
    "credit_current",
    "variance",
]:
    display_df[col] = display_df[col].map(
        lambda value: (
            f"${value:,.2f}"
            if pd.notna(value)
            else ""
        )
    )


# Format percentage column
display_df["percentage"] = display_df["percentage"].map(
    lambda value: (
        f"{value:,.2f}%"
        if pd.notna(value)
        else ""
    )
)


# ============================================================
# DISPLAY RESULTS
# ============================================================
print("Revenue 2-Year Comparison DataFrame:")

display(display_df)

Revenue 2-Year Comparison DataFrame:

,fund,fund_name,function,function_name,credit_prev,credit_current,variance,percentage
0,001,<NA>,0000,<NA>,"$243,434,413.79","$4,162,680.46","$-239,271,733.33",-98.29%
1,001,<NA>,1100,<NA>,,$0.00,,
2,001,<NA>,1110,<NA>,,"$6,163.00",,
3,001,<NA>,1120,<NA>,,$0.00,,
4,001,<NA>,1130,<NA>,,"$2,786.76",,
5,001,<NA>,1140,<NA>,,$0.00,,
6,001,<NA>,1190,<NA>,,"$4,474.78",,
7,001,<NA>,1210,<NA>,,$0.00,,
8,001,<NA>,1230,<NA>,,"$988,446.14",,
9,001,<NA>,1231,<NA>,,$0.00,,

:

## GL_2YR_EXP

In [ ]:
money_cols = ["debit", "credit", "balance"]


def prepare_expense_location(df):
    df = df.copy()

    # Split "Fund: 001 - General" into its code and name.
    fund_parts = df["fund"].astype("string").str.extract(
        r"^\s*Fund:\s*(?P<fund>\S+)\s*-\s*(?P<fund_name>.*?)\s*$"
    )
    df["fund"] = fund_parts["fund"].fillna(
        df["fund"].astype("string").str.strip()
    )
    df["fund_name"] = fund_parts["fund_name"]

    # Split "Function: 0000 - Not Applicable" into its code and name.
    function_parts = df["function"].astype("string").str.extract(
        r"^\s*Function:\s*(?P<function>\S+)\s*-\s*(?P<function_name>.*?)\s*$"
    )
    df["function"] = function_parts["function"].fillna(
        df["function"].astype("string").str.strip()
    )
    df["function_name"] = function_parts["function_name"]

    for col in money_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Total each fund and function combination within the year.
    return (
        df.groupby(["fund", "function"], as_index=False, dropna=False)
        .agg(
            fund_name=("fund_name", "first"),
            function_name=("function_name", "first"),
            debit=("debit", lambda values: values.sum(min_count=1)),
            credit=("credit", lambda values: values.sum(min_count=1)),
            balance=("balance", lambda values: values.sum(min_count=1)),
        )
    )


current = prepare_expense_location(exp_loc_df)
previous = prepare_expense_location(exp_loc_prev_df)

exp_2yr_comparison = current.merge(
    previous,
    on=["fund", "function"],
    how="outer",
    suffixes=("_current", "_prev"),
    validate="one_to_one",
)

# Prefer current-year names; use previous-year names where needed.
exp_2yr_comparison["fund_name"] = (
    exp_2yr_comparison["fund_name_current"]
    .fillna(exp_2yr_comparison["fund_name_prev"])
)
exp_2yr_comparison["function_name"] = (
    exp_2yr_comparison["function_name_current"]
    .fillna(exp_2yr_comparison["function_name_prev"])
)

# Compare current-year debit with previous-year debit.
exp_2yr_comparison["variance"] = (
    exp_2yr_comparison["debit_current"]
    - exp_2yr_comparison["debit_prev"]
)

exp_2yr_comparison["percentage"] = (
    exp_2yr_comparison["variance"]
    .div(exp_2yr_comparison["debit_prev"].replace(0, float("nan")))
    .mul(100)
)

exp_2yr_comparison = exp_2yr_comparison[
    [
        "fund",
        "fund_name",
        "function",
        "function_name",
        "debit_prev",
        "debit_current",
        "variance",
        "percentage",
    ]
]

# Format a copy for display without requiring jinja2.
display_df = exp_2yr_comparison.head(10).copy()

for col in ["debit_prev", "debit_current", "variance"]:
    display_df[col] = display_df[col].map(
        lambda value: f"${value:,.2f}" if pd.notna(value) else ""
    )

display_df["percentage"] = display_df["percentage"].map(
    lambda value: f"{value:,.2f}%" if pd.notna(value) else ""
)

print("Expense Location Comparison DataFrame:")
display(display_df)

Expense Location Comparison DataFrame:

,fund,fund_name,function,function_name,debit_prev,debit_current,variance,percentage
0,001,<NA>,0000,<NA>,$71.60,"$2,108.91","$2,037.31","2,845.41%"
1,001,<NA>,1100,<NA>,"$70,628.84","$63,637.18","$-6,991.66",-9.90%
2,001,<NA>,1110,<NA>,"$37,212,894.10","$794,015.04","$-36,418,879.06",-97.87%
3,001,<NA>,1120,<NA>,"$9,932,868.15","$73,427.10","$-9,859,441.05",-99.26%
4,001,<NA>,1130,<NA>,"$18,907,119.00","$398,542.44","$-18,508,576.56",-97.89%
5,001,<NA>,1140,<NA>,"$24,623.99","$21,861.06","$-2,762.93",-11.22%
6,001,<NA>,1190,<NA>,"$7,830,905.12","$1,050,809.20","$-6,780,095.92",-86.58%
7,001,<NA>,1210,<NA>,"$651,234.17","$14,148.93","$-637,085.24",-97.83%
8,001,<NA>,1230,<NA>,"$29,259,789.25","$48,614.77","$-29,211,174.48",-99.83%
9,001,<NA>,1231,<NA>,"$48,689.24",,,

:

## Vendor_Det

In [ ]:
vendor_det_df = exp_loc_df.loc[exp_loc_df["debit"] > 0, [
    "fund",
    "fund_name",
    "function",
    "function_name",
    "peid",
    "description",
    "debit",
    "credit"
]].copy()

print("Vendor Payments DataFrame:")
display(vendor_det_df.head(10))

Vendor Payments DataFrame:

,fund,fund_name,function,function_name,peid,description,debit,credit
53,001,General,0000,Not Applicable,N/A..N/A,RECLASS MISC PY INCOME 8/18/2,2081.74,0.00
66,001,General,0000,Not Applicable,N/A..N/A,RECLASS CR206501 CATAPULT LEAR,27.17,0.00
69,001,General,1100,Regular Instruction,V000236,FURST FLORIST I Green Plants,144.75,0.00
70,001,General,1100,Regular Instruction,V013769,GRADUATE SERVIC Open order for,268.50,0.00
71,001,General,1100,Regular Instruction,V013769,GRADUATE SERVIC Increase per P,582.75,0.00
72,001,General,1100,Regular Instruction,V000858,FLINN SCIENTIFI Goggle Sanitiz,838.95,0.00
73,001,General,1100,Regular Instruction,V000858,FLINN SCIENTIFI Freight,116.42,0.00
74,001,General,1100,Regular Instruction,V026955,SWEETWATER SOUN Casio 88-key D,679.00,0.00
75,001,General,1100,Regular Instruction,V026955,SWEETWATER SOUN Casio Black St,159.00,0.00
76,001,General,1100,Regular Instruction,V026955,SWEETWATER SOUN Casio Px-S1000,119.00,0.00

:

## Vendor_Sum

In [ ]:

vendor_summary_df = (
    exp_loc_df[["peid", "description", "debit"]]
    .groupby(["peid", "description"], as_index=False)
    .agg(
        debit=("debit", "sum"),
        volume_count=("debit", "size"),
        
    )
)

print("Vendor Summary DataFrame:")
display(vendor_summary_df.head(10))

Vendor Summary DataFrame:

       peid                     description     debit  volume_count
0  N/A..N/A    1.1130.3362.000         GRS.   2000.00             1
1  N/A..N/A    1.2213.3305.500         GRS.   3708.72             1
2  N/A..N/A     Adj Expense to Correct Code    463.94             2
3  N/A..N/A  Adj. Expense to Correct Budget    590.00             2
4  N/A..N/A    Adj. Expense to Correct Code 159463.61            32
5  N/A..N/A  Adj. Expense to Correct Functi    986.74             6
6  N/A..N/A  Adj. Expense to Grant per ODEW      0.00             1
7  N/A..N/A  Advance Funds for Cash Balance      0.00             1
8  N/A..N/A           Advances for November      0.00             5
9  N/A..N/A            Advances for October      0.00             2

:

:

## Vendor_Dup

In [ ]:
duplicated_vendors_df = (
    vendor_summary_df[
        vendor_summary_df.duplicated(subset=["description"], keep=False)
    ]
)

print("Duplicated Vendors DataFrame:")
display(duplicated_vendors_df.head(10))

Duplicated Vendors DataFrame:

Empty DataFrame
Columns: [peid, description, debit, volume_count]
Index: []

:

:

## GL_Gaps

In [ ]:
checks = exp_loc_df[["fund", "function", "ck_no"]].copy()
checks["ck_no"] = pd.to_numeric(
    checks["ck_no"], errors="coerce"
)

checks = (
    checks.dropna(subset=["ck_no"])
    .drop_duplicates()
    .sort_values(["fund", "function", "ck_no"])
)

checks["gap_start"] = checks.groupby(
    ["fund", "function"]
)["ck_no"].shift()

checks["gap_end"] = checks["ck_no"]
checks["missing"] = checks["gap_end"] - checks["gap_start"] - 1

check_number_gaps_df = (
    checks.loc[
        checks["missing"] > 0,
        ["gap_start", "gap_end", "missing"]
    ]
    .astype("Int64")
    .reset_index(drop=True)
)

display(check_number_gaps_df.head(10))

   gap_start  gap_end  missing
0     288760   288790       29
1     288790   288796        5
2     288796   288882       85
3     288882   288941       58
4     288941   289151      209
5     289151   289283      131
6     289283   289506      222
7     289506   289531       24
8     289531   289546       14
9     289546   289820      273

:

:

## GL_Confirmable_Receipts

In [ ]:
confirmable_receipts_columns = [
    "fund",
    "fund_name",
    "special_cost_center",
    "opu",
    "function",
    "account",
    "gl_reference",
    "description",
    "posting_date",
    "ss",
    "ref2",
    "debit",
    "credit",
]

confirmable_receipts_df = rev_loc_df[confirmable_receipts_columns].copy()

print("Confirmable Receipts DataFrame:")
display(confirmable_receipts_df.head(10))

Revenue Location DataFrame:

,fund,fund_name,special_cost_center,opu,function,account,gl_reference,description,posting_date,ss,ref2,debit,credit
0,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,8864,Cash Receipts I gainwell techn,7/10/2025,CR,129078,0.00,64762.98
1,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,8874,Cash Receipts I gainwell techn,7/24/2025,CR,129094,0.00,50983.01
2,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,8894,Cash Receipts I gainwell techn,8/14/2025,CR,129144,0.00,10328.18
3,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,8906,Cash Receipts I gainwell techn,8/22/2025,CR,129172,0.00,1825686.12
4,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,9059,Cash Receipts I gainwell techn,10/2/2025,CR,129698,0.00,10767.82
5,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,9084,Cash Receipts I gainwell techn,10/9/2025,CR,129799,0.00,12343.07
6,001,General,1925,000,0000,001-0000-4412000-1925-000000-000-00,9113,Cash Receipts I gainwell tech,10/17/2025,CR,129896,0.00,1736.10
7,001,General,1925,000,0000,001-0000-4422100-1925-000000-000-00,9166,Cash Receipts I gainwell techn,11/30/2025,CR,130101,0.00,7791.08
8,001,General,1925,000,0000,001-0000-4422100-1925-000000-000-00,9206,Cash Receipts I gainwell techn,12/4/2025,CR,130237,0.00,8119.08
9,001,General,1925,000,0000,001-0000-4422100-1925-000000-000-00,9274,Cash Receipts I gainwell techn,12/26/2025,CR,130442,0.00,24335.41

:

:

## GL Transactions

In [ ]:
gl_transactions_columns = [
    "fund",
    "fund_name",
    "special_cost_center",
    "opu",
    "function",
    "function_name",
    "account",
    "gl_reference",
    "description",
    "posting_date",
    "ss",
    "ref2",
    "peid",
    "ck_id",
    "ck_no",
    "debit",
    "credit",
    "balance",
    "type",
]

gl_transactions_df = pd.concat(
    [
        exp_loc_df.assign(type="expense"),
        rev_loc_df.assign(type="revenue"),
    ],
    ignore_index=True,
)

gl_transactions_df = gl_transactions_df.loc[
    gl_transactions_df["debit"] > 0, gl_transactions_columns
].copy()

print("Combined Expense and Revenue DataFrame:")
display(gl_transactions_df.head(10))

Combined Expense and Revenue DataFrame:

,fund,fund_name,special_cost_center,opu,function,function_name,account,gl_reference,description,posting_date,ss,ref2,peid,ck_id,ck_no,debit,credit,balance,type
53,001,General,2001,000,0000,Not Applicable,001-0000-4530000-2001-000000-000-00,JE09641,RECLASS MISC PY INCOME 8/18/2,3/27/2026,JE,NaN,N/A..N/A,NaN,NaN,2081.74,0.00,2081.74,expense
66,001,General,1114,500,0000,Not Applicable,001-0000-4530000-1114-000000-500-00,JE09586,RECLASS CR206501 CATAPULT LEAR,2/13/2026,JE,NaN,N/A..N/A,NaN,NaN,27.17,0.00,27.17,expense
69,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN01720830,FURST FLORIST I Green Plants,7/2/2025,OH,P046434,V000236,AP,00288796,144.75,0.00,144.75,expense
70,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN25239,GRADUATE SERVIC Open order for,7/8/2025,OH,P046498,V013769,AP,00288941,268.50,0.00,268.50,expense
71,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN25355,GRADUATE SERVIC Increase per P,7/8/2025,OH,P046498,V013769,AP,00288941,582.75,0.00,582.75,expense
72,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN3145502,FLINN SCIENTIFI Goggle Sanitiz,7/2/2025,OH,P046703,V000858,AP,00288790,838.95,0.00,838.95,expense
73,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN3145502,FLINN SCIENTIFI Freight,7/2/2025,OH,P046703,V000858,AP,00288790,116.42,0.00,116.42,expense
74,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio 88-key D,7/2/2025,OH,P046612,V026955,AP,00288882,679.00,0.00,679.00,expense
75,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio Black St,7/2/2025,OH,P046612,V026955,AP,00288882,159.00,0.00,159.00,expense
76,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio Px-S1000,7/2/2025,OH,P046612,V026955,AP,00288882,119.00,0.00,119.00,expense

:

:

## Check_Register_Detail

In [ ]:
checks_detail_df = exp_loc_df.loc[exp_loc_df["ck_no"].notnull(), [
    "ck_no",
    "ck_id",
    "fund",
    "fund_name",
    "special_cost_center",
    "opu",
    "function",
    "function_name",
    "account",
    "gl_reference",
    "description",
    "posting_date",
    "ss",
    "ref2",
    "peid",
    "debit",
]].copy()   

print("Checks Detail DataFrame:")
display(checks_detail_df.head(10))

Checks DataFrame:

,ck_no,ck_id,fund,fund_name,special_cost_center,opu,function,function_name,account,gl_reference,description,posting_date,ss,ref2,peid,debit
69,00288796,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN01720830,FURST FLORIST I Green Plants,7/2/2025,OH,P046434,V000236,144.75
70,00288941,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN25239,GRADUATE SERVIC Open order for,7/8/2025,OH,P046498,V013769,268.50
71,00288941,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5510000-1530-000000-271-00,IN25355,GRADUATE SERVIC Increase per P,7/8/2025,OH,P046498,V013769,582.75
72,00288790,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN3145502,FLINN SCIENTIFI Goggle Sanitiz,7/2/2025,OH,P046703,V000858,838.95
73,00288790,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN3145502,FLINN SCIENTIFI Freight,7/2/2025,OH,P046703,V000858,116.42
74,00288882,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio 88-key D,7/2/2025,OH,P046612,V026955,679.00
75,00288882,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio Black St,7/2/2025,OH,P046612,V026955,159.00
76,00288882,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN45723104,SWEETWATER SOUN Casio Px-S1000,7/2/2025,OH,P046612,V026955,119.00
77,00288760,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN4650579,BARNES & NOBLE Animal Farm,7/2/2025,OH,P046598,V005670,119.85
80,00288760,AP,001,General,1530,271,1100,Regular Instruction,001-1100-5511000-1530-000000-271-00,IN4650590,BARNES & NOBLE Glass Castle,7/2/2025,OH,P046604,V005670,303.80

:

:

## Check_register_Summary

In [ ]:
checks_sum_df = exp_loc_df.loc[
    exp_loc_df["ck_no"].notna(),
    ["ck_no", "posting_date", "description", "peid", "debit"],
].copy()

checks_sum_df["volume"] = (
    checks_sum_df.groupby("ck_no")["ck_no"].transform("size")
)

print("Checks Summary DataFrame:")
display(checks_sum_df.head(10))

Checks Summary DataFrame:

,ck_no,posting_date,description,peid,debit,volume
69,00288796,7/2/2025,FURST FLORIST I Green Plants,V000236,144.75,6
70,00288941,7/8/2025,GRADUATE SERVIC Open order for,V013769,268.50,2
71,00288941,7/8/2025,GRADUATE SERVIC Increase per P,V013769,582.75,2
72,00288790,7/2/2025,FLINN SCIENTIFI Goggle Sanitiz,V000858,838.95,3
73,00288790,7/2/2025,FLINN SCIENTIFI Freight,V000858,116.42,3
74,00288882,7/2/2025,SWEETWATER SOUN Casio 88-key D,V026955,679.00,3
75,00288882,7/2/2025,SWEETWATER SOUN Casio Black St,V026955,159.00,3
76,00288882,7/2/2025,SWEETWATER SOUN Casio Px-S1000,V026955,119.00,3
77,00288760,7/2/2025,BARNES & NOBLE Animal Farm,V005670,119.85,20
80,00288760,7/2/2025,BARNES & NOBLE Glass Castle,V005670,303.80,20

:

:

# Export to Excel

In [ ]:
def add_filters_and_autofit(tab, verbose):
    """
    Add filters to the tab and autofit the columns.
    
    Parameters:
        tab (xlwings sheet): The tab to add filters and autofit.
        verbose (str): 't' or 'f' to print the number of records in each dataframe.
    Returns:
        None
    """
    # find the last column and row
    last_col = tab.range('A1').expand('table').last_cell.column
    last_row = tab.range('A1').expand('table').last_cell.row
    if verbose == 't':
        print(f"\tLast Column: {last_col}, Last Row: {last_row}")

    # add filters from A1 to last_col and last_row
    tab.range((1, 1), (last_row, last_col)).api.AutoFilter(Field=1)
    # autofit the columns
    tab.autofit()

    # set column width to 50 for any columns that are wider than 50
    for col in range(1, last_col + 1):
        if tab.range(1, col).column_width > 50:
            tab.range(1, col).column_width = 50

    return None

:

:

In [ ]:
with xw.App() as xl:
    wb = xw.Book()
    # add a chart_of_accts tab
    fund_report_comparison_tab = wb.sheets.add('fund_report_comparison', after=None)
    # set columns A and B as text
    fund_report_comparison_tab.range('A:B').number_format = '@'
    # columns C-H as currency
    fund_report_comparison_tab.range('C:J').number_format = '$#,##0.00'
    # add the coa_df to the tab
    fund_report_comparison_tab.range('A1').options(index=False).value = fund_report_comparison 
    # add filters and autofit the columns
    add_filters_and_autofit(fund_report_comparison_tab, 't')

    # add an gl_expenses tab
    fund_report_scc_comparison_tab = wb.sheets.add('fund_report_scc_comparison', after='fund_report_comparison')
    # add the expenses_by_gl to the tab
    # set columns A as text
    fund_report_scc_comparison_tab.range('A:C').number_format = '@'
    # columns B-J as currency
    fund_report_scc_comparison_tab.range('D:K').number_format = '$#,##0.00'
    
    fund_report_scc_comparison_tab.range('A1').options(index=False).value = fund_report_scc_comparison
    # add filters and autofit the columns
    add_filters_and_autofit(fund_report_scc_comparison_tab, 't')

    # add vendor_activity_exp tab
    rev_2yr_comparison = wb.sheets.add('gl_rev_2yr', after='fund_report_scc_comparison')
    # set A:D as text
    rev_2yr_comparison.range('A:D').number_format = '@'
    # set E:G as currency
    rev_2yr_comparison.range('E:G').number_format = '$#,##0.00'
    #SET H as percentage
    rev_2yr_comparison.range('H:H').number_format = '0.00%'
    # add the exp_by_vendor to the tab
    rev_2yr_comparison.range('A1').options(index=False).value = rev_2yr_df
    # add filters and autofit the columns
    add_filters_and_autofit(rev_2yr_comparison, 't')

    # add vendor_activity_exp tab
    exp_2yr_comparison = wb.sheets.add('gl_exp_2yr', after='gl_rev_2yr')
    # set A:D as text
    exp_2yr_comparison.range('A:D').number_format = '@'
    # set E:G as currency
    exp_2yr_comparison.range('E:G').number_format = '$#,##0.00'
    #SET H as percentage
    exp_2yr_comparison.range('H:H').number_format = '0.00%'
    # add the exp_by_vendor to the tab
    exp_2yr_comparison.range('A1').options(index=False).value = exp_2yr_df
    # add filters and autofit the columns
    add_filters_and_autofit(exp_2yr_comparison, 't')

    # add vendor_detail_tab
    gl_vendor_det_tab = wb.sheets.add('vendor_payments_df', after='gl_exp_2yr')
    # set A:E as text
    gl_vendor_det_tab.range('A:F').number_format = '@'
    # set F and G as currency
    gl_vendor_det_tab.range('G:H').number_format = '$#,##0.00'
    # add the gl_vendor to the tab
    gl_vendor_det_tab.range('A1').options(index=False).value = gl_vendor
    # add filters and autofit the columns
    add_filters_and_autofit(gl_vendor_det_tab, 't')

    # add gl_vendor_sum_tab
    gl_vendor_sum_tab = wb.sheets.add('gl_vendor_sum', after='vendor_payments_df')
    # set A:B as text
    gl_vendor_sum_tab.range('A:B').number_format = '@'
    # # set C and D as accounting
    gl_vendor_sum_tab.range('C:D').number_format = '$#,##0.00'
    # add the gl_vendor_sum to the tab
    gl_vendor_sum_tab.range('A1').options(index=False).value = vendor_summary_df
    # add filters and autofit the columns  
    add_filters_and_autofit(gl_vendor_sum_tab, 't')

    # add gl_vendor_dup tab
    gl_vendor_dup_tab = wb.sheets.add('gl_vendor_dup', after='gl_vendor_sum')
    # set A:B as text
    gl_vendor_dup_tab.range('A:B').number_format = '@'
    # set C and D as currency
    gl_vendor_dup_tab.range('C:D').number_format = '$#,##0.00'
    # add the gl_vendor_dup to the tab
    gl_vendor_dup_tab.range('A1').options(index=False).value = gl_vendor_dup
    # add filters and autofit the columns
    add_filters_and_autofit(gl_vendor_dup_tab, 't')

    # add gl_gaps tab
    gl_gaps_tab = wb.sheets.add('gl_gaps', after='gl_vendor_dup')
    # set A:B as text
    gl_gaps_tab.range('A:B').number_format = '@'
    # set C and D as currency
    gl_gaps_tab.range('C:C').number_format = '#,##0'
    # add the gl_gaps to the tab
    gl_gaps_tab.range('A1').options(index=False).value = check_number_gaps_df
    # add filters and autofit the columns
    add_filters_and_autofit(gl_gaps_tab, 't')

    # add confirmable_receipts_df tab
    confirmable_receipts_tab = wb.sheets.add('confirmable_receipts', after='gl_gaps')
    # set A:AK as text
    confirmable_receipts_tab.range('A:K').number_format = '@'
    # set I as Date
    confirmable_receipts_tab.range('I:I').number_format = 'yyyy-mm-dd'
    # set P and Q as currency
    confirmable_receipts_tab.range('L:M').number_format = '$#,##0.00'
    # add the confirmable_receipts_df to the tab
    confirmable_receipts_tab.range('A1').options(index=False).value = confirmable_receipts_df
    # add filters and autofit the columns
    add_filters_and_autofit(confirmable_receipts_tab, 't')

    # add gl_transactions_df tab
    full_gl_tab = wb.sheets.add('gl_transactions', after='confirmable_receipts')
    # set A:AJ as text
    full_gl_tab.range('A:S').number_format = '@'
    # set  C and W as as Date
    full_gl_tab.range('J:J').number_format = 'yyyy-mm-dd'  
    # # set O and P as currency 
    full_gl_tab.range('P:S').number_format = '$#,##0.00'
    # add the vendor_compare_explain to the tab
    full_gl_tab.range('A1').options(index=False).value = gl_transactions_df
    # add filters and autofit the columns
    add_filters_and_autofit(full_gl_tab, 't')

    # add checks_detail_df tab
    checks_detail_tab = wb.sheets.add('checks_detail', after='gl_transactions')
    # set A:S as text
    checks_detail_tab.range('A:O').number_format = '@'
    # set J as Date
    checks_detail_tab.range('L:L').number_format = 'yyyy-mm-dd'
    # set P:S as currency
    checks_detail_tab.range('P:P').number_format = '$#,##0.00'
    # add the checks_detail_df to the tab
    checks_detail_tab.range('A1').options(index=False).value = checks_detail_df
    # add filters and autofit the columns
    add_filters_and_autofit(checks_detail_tab, 't')

    # add checks_sum_df tab
    checks_sum_tab = wb.sheets.add('checks_sum', after='checks_detail')
    # set A:O as text
    checks_sum_tab.range('A:D').number_format = '@'
    # set L as Date
    checks_sum_tab.range('B:B').number_format = 'yyyy-mm-dd'
    # set P as currency
    checks_sum_tab.range('E:E').number_format = '$#,##0.00'
    # set F as number
    checks_sum_tab.range('F:F').number_format = '0'
    # add the checks_sum_df to the tab
    checks_sum_tab.range('A1').options(index=False).value = checks_sum_df
    # add filters and autofit the columns
    add_filters_and_autofit(checks_sum_tab, 't')
    
    wb.save("Dayton_Public_Schools_GL_Reports_2026.xlsx")
    wb.close()

:

: